spring.datasource.url = jdbc:postgresql://localhost:5432/travlbuds
spring.datasource.username =owenren
spring.datasource.password =

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql =true

groq.api.key=${GROQ_API_KEY}
groq.model=llama-3.3-70b-versatile